
networks:
  app-network:
    driver: bridge

services:
  
  db:
    image: davirdasilva/meu_banco:v1
    ports:
      - "4040:3306"
    networks:
      - app-network

  app:
    image: davirdasilva/meu_site:v1
    environment:
    - DB_HOST=localhost
    - DB_USER=root
    - DB_DATABASE=aquatech
    - DB_PASSWORD=urubu100
    - DB_PORT=4040
    links:
    - db
    ports:
      - "8080:3333"
    networks:
      - app-network